# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.9"
gem "guard-rspec", "~> 4.7"
gem "simplecov", "~> 0.18.5"
gem "pry-byebug", "~> 3.9"

gem "benchmark-ips", "~> 2.8"

gem "pastel", "~> 0.8.0"
