# More info at https://github.com/guard/guard#readme

guard_options = {
  cmd:            'clear && bundle exec rspec spec/ --order defined --fail-fast  -f p',
  all_after_pass: false,
  failed_mode:    :focus
}

guard :rspec, guard_options do
  require "guard/rspec/dsl"
  dsl = Guard::RSpec::Dsl.new(self)

  # Feel free to open issues for suggestions and improvements

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)
end
