version: '3'

services:
  web:
    build: './src'
    volumes:
      - ./src:/usr/src/app
    ports:
      - 3000:3000
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
    - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server

  webpack_dev_server:
    build: './src'
    command: ./bin/webpack-dev-server
    volumes:
      - ./src:/usr/src/app
    ports:
      - 3035:3035
    env_file:
      - .env/development/database
      - .env/development/web
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  database:
    image: postgres:13.1
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
