# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec'
gem 'pry'
gem 'pry-nav'
gem 'reek'
gem 'guard-rspec', require: false
gem 'rb-readline' # for guard

gem 'contracts'
gem 'yard-contracts'
