version: "3"
services:
  my_nginx_kata:
    container_name: my_nginx_kata_container
    build: ./web_server
    image: my_nginx_kata_image
    ports:
      - "80:80"

  my_web_app_kata:
    container_name: my_web_app_kata_container
    image: my_web_app_kata_image
    build: ./web_app
    environment:
      - RACK_ENV=production
