# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'guard-rspec', require: false
gem 'pry-byebug'
gem 'rb-readline' # for guard
gem 'reek'
gem 'rspec'
gem 'rubocop', '~> 1.24'
