# frozen_string_literal: true
source 'https://rubygems.org' do
  gem 'rspec'
  gem 'pry'
  gem 'pry-nav'
  gem 'reek'
  gem 'guard-rspec', require: false
  gem 'rb-readline' # for guard

  gem 'contracts'
  gem 'yard-contracts'

  # Performance
  gem 'benchmark-ips'
  gem 'memory_profiler'
  gem 'benchmark_driver'
end
