# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"
gem "guard-rspec", "~> 4.7"
gem "simplecov", "~> 0.19.1"
gem "pry-byebug", "~> 3.9"
